### ISSUE TITLE
Did it work?

### ISSUE THREAD

**Issue by brunobasto** [Yukiiro-Nite/cameratopebble#1]

**Comment by Yukiiro-Nite** [comment]
Yes it did at the time. Are you trying to get it working for yourself?

**Comment by brunobasto** [comment]
I think I will at some point. Just got a cheap Pebble and have some ideas of apps to implement. Got here by looking for code examples and found it to be a bold idea.

I imagine it's a low frame rate, right?

**Comment by brunobasto** [comment]
Do you still have the code for the web server?

**Comment by Yukiiro-Nite** [comment]
Yes I do have the code for that. I can upload it in the next day or so. 

It is pretty low frame rate, and there were some challenges around getting an entire image onto the pebble.

**Comment by brunobasto** [comment]
> It is pretty low frame rate, and there were some challenges around getting an entire image onto the pebble.

I can imagine

> Yes I do have the code for that. I can upload it in the next day or so.

I appreciate. Thank you.

**Comment by Yukiiro-Nite** [comment]
I've added a cleaner version of the old server code: https://github.com/Yukiiro-Nite/cameratopebble/tree/5e3ef2c1aa5f3bf74d40f26e9f77c0d566694117/server

It could still use some work, but it should be enough to get images to your watch if you can get the app to run. You'll also need to change the [url](https://github.com/Yukiiro-Nite/cameratopebble/blob/master/src/pkjs/app.js#L32) to point to where ever you run your server.
